/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FrmMakingPurchases extends javax.swing.JFrame {

    /**
     * Creates new form FrmMakingPurchases
     */
    public FrmMakingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblLnst1 = new javax.swing.JLabel();
        lblLnst2 = new javax.swing.JLabel();
        lblLemonMacaroon = new javax.swing.JLabel();
        lblBlueberryMacaroon = new javax.swing.JLabel();
        lblRaspberryMacaroon = new javax.swing.JLabel();
        lblLimeMacaroon = new javax.swing.JLabel();
        lblBananaMacaroon = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        txtLemonMacaroon = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lblTaxesValue = new javax.swing.JLabel();
        lblSubtotalValue = new javax.swing.JLabel();
        lblGrandTotalValue = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtBlueberryMacaroon = new javax.swing.JTextField();
        txtRaspberryMacaroon = new javax.swing.JTextField();
        txtLimeMacaroon = new javax.swing.JTextField();
        txtBananaMacaroon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Viner Hand ITC", 0, 28)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 255));
        lblHeader.setText("Madeleine's Macaroons");

        lblLnst1.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblLnst1.setForeground(new java.awt.Color(102, 102, 255));
        lblLnst1.setText("Enter the number of each macaoon that you would");

        lblLnst2.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblLnst2.setForeground(new java.awt.Color(102, 102, 255));
        lblLnst2.setText("like to purchase and click Calculatte.");

        lblLemonMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblLemonMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        lblLemonMacaroon.setText("Lemon Macaroons ($1.99):");

        lblBlueberryMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblBlueberryMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        lblBlueberryMacaroon.setText("Blueberry Macaroons ($1.79):");

        lblRaspberryMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblRaspberryMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        lblRaspberryMacaroon.setText("Raspberry Macaroons ($1.99):");

        lblLimeMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblLimeMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        lblLimeMacaroon.setText("Lime Macaroons ($1.79):");

        lblBananaMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblBananaMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        lblBananaMacaroon.setText("Banana Macaroons ($2.29):");

        lblTaxes.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblTaxes.setForeground(new java.awt.Color(102, 102, 255));
        lblTaxes.setText("Taxes (13%):");

        lblSubtotal.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(102, 102, 255));
        lblSubtotal.setText("Subtotal:");

        lblGrandTotal.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(102, 102, 255));
        lblGrandTotal.setText("Grand Total:");

        txtLemonMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        txtLemonMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        txtLemonMacaroon.setText("0");

        btnCalculate.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(102, 102, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblTaxesValue.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblTaxesValue.setForeground(new java.awt.Color(102, 102, 255));
        lblTaxesValue.setText("$0.00");

        lblSubtotalValue.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblSubtotalValue.setForeground(new java.awt.Color(102, 102, 255));
        lblSubtotalValue.setText("$0.00");

        lblGrandTotalValue.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        lblGrandTotalValue.setForeground(new java.awt.Color(102, 102, 255));
        lblGrandTotalValue.setText("$0.00");

        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2025-10-19 171124.jpg"))); // NOI18N

        txtBlueberryMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        txtBlueberryMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        txtBlueberryMacaroon.setText("0");

        txtRaspberryMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        txtRaspberryMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        txtRaspberryMacaroon.setText("0");

        txtLimeMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        txtLimeMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        txtLimeMacaroon.setText("0");

        txtBananaMacaroon.setFont(new java.awt.Font("Viner Hand ITC", 0, 16)); // NOI18N
        txtBananaMacaroon.setForeground(new java.awt.Color(102, 102, 255));
        txtBananaMacaroon.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTaxes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTaxesValue)
                    .addComponent(lblGrandTotalValue)
                    .addComponent(lblSubtotalValue))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRaspberryMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBlueberryMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLimeMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBananaMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLemonMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBlueberryMacaroon)
                            .addComponent(lblLemonMacaroon)
                            .addComponent(lblRaspberryMacaroon)
                            .addComponent(lblLimeMacaroon)
                            .addComponent(lblBananaMacaroon))
                        .addGap(58, 58, 58)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(261, Short.MAX_VALUE)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblLnst1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lblLnst2)))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLnst1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLnst2))
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLemonMacaroon)
                            .addComponent(txtLemonMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBlueberryMacaroon)
                            .addComponent(txtBlueberryMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaspberryMacaroon)
                            .addComponent(txtRaspberryMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLimeMacaroon)
                            .addComponent(txtLimeMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTaxes)
                        .addGap(30, 30, 30)
                        .addComponent(lblSubtotal)
                        .addGap(32, 32, 32)
                        .addComponent(lblGrandTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTaxesValue)
                        .addGap(30, 30, 30)
                        .addComponent(lblSubtotalValue)
                        .addGap(32, 32, 32)
                        .addComponent(lblGrandTotalValue)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBananaMacaroon)
                    .addComponent(txtBananaMacaroon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        //Variables
        int Lemon;
        int Blueberry;
        int Raspberry;
        int Lime;
        int Banana;
        double taxes;
        double subtotal;
        double grandTotal;
        
        //get input from user
        Lemon = Integer.parseInt(txtLemonMacaroon.getText());
        Blueberry = Integer.parseInt(txtBlueberryMacaroon.getText());
        Raspberry = Integer.parseInt(txtRaspberryMacaroon.getText());
        Lime = Integer.parseInt(txtLimeMacaroon.getText());
        Banana = Integer.parseInt(txtBananaMacaroon.getText());
        
        //CONSTANTS PRICES AND TAX
        final double LEMON_MACA_PRICE = 1.99;
        final double BLUEBERRY_MACA_PRICE = 1.79;
        final double RASPBERRY_MACA_PRICE = 1.99;
        final double LIME_MACA_PRICE = 1.79;
        final double BANANA_MACA_PRICE = 2.29;
        final double TAX = 0.13;
        
        //Calculations
        subtotal = (LEMON_MACA_PRICE*Lemon) + (BLUEBERRY_MACA_PRICE*Blueberry) + (RASPBERRY_MACA_PRICE*Raspberry) + (LIME_MACA_PRICE*Lime) + (BANANA_MACA_PRICE*Banana);
        taxes = subtotal*TAX;
        grandTotal = subtotal + taxes;
        //Round values
        double taxesRound = (double) Math.round(taxes*100)/100;
        double subtotalRound = (double) Math.round(subtotal*100)/100;
        double grandTotalRound = (double) Math.round(grandTotal*100)/100;
        //print output
        lblTaxesValue.setText(String.valueOf("$" + taxesRound));
        lblSubtotalValue.setText(String.valueOf("$" + subtotalRound));
        lblGrandTotalValue.setText(String.valueOf("$" + grandTotalRound));
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMakingPurchases().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblBananaMacaroon;
    private javax.swing.JLabel lblBlueberryMacaroon;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGrandTotalValue;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLemonMacaroon;
    private javax.swing.JLabel lblLimeMacaroon;
    private javax.swing.JLabel lblLnst1;
    private javax.swing.JLabel lblLnst2;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblRaspberryMacaroon;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalValue;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTaxesValue;
    private javax.swing.JTextField txtBananaMacaroon;
    private javax.swing.JTextField txtBlueberryMacaroon;
    private javax.swing.JTextField txtLemonMacaroon;
    private javax.swing.JTextField txtLimeMacaroon;
    private javax.swing.JTextField txtRaspberryMacaroon;
    // End of variables declaration//GEN-END:variables
}
